-- AlterTable
ALTER TABLE "LeaveType" ADD COLUMN     "carryForward" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "description" TEXT,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "maxDays" DROP NOT NULL,
ALTER COLUMN "paid" SET DEFAULT true;
